### ISSUE TITLE
Sometimes data is not displayed, when expanding a node

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sirixdb/sirix-svelte-frontend#274]
It happens in the `cityofchicago` resource, that the server sends a reply, but the expanded subtree is not displayed:

![Screenshot from 2020-10-10 13-08-41](https://user-images.githubusercontent.com/1202851/95653544-c8630880-0af9-11eb-801b-a4f514701355.png)

**Comment by mosheduminer** [comment]
Very strange, I've never seen this before. I will need more context to find the problem.

**Comment by mosheduminer** [comment]
I've reproduced this with another file, but I will need to investigate further.

**Comment by mosheduminer** [comment]
It appears to me that this issue occurs only when maxLevel is set to 1 (as in the URL in the screenshot you posted). A simple workaround would be to not allow setting lazy-loading to `1`. I think this is a satisfactory solution, do you agree?

**Comment by JohannesLichtenberger** [comment]
Wouldn't this mean that only the children from the context-node are fetched from the server? So it should be a valid option?

**Comment by mosheduminer** [comment]
I'm not sure what you mean, can you elaborate?

**Comment by mosheduminer** [comment]
To elaborate further on the bug, the frontend appliaction is assuming that when the metadata is returned from the API, the `value` field of a metadata object with `type` `object` will be an _array_, not an object. This is in fact how the API behaves. However, when `maxLevel=1`, the `value` field is an empty object, which is not what the application expects.

I should be able to work around this issue, without needing to limit the possible values for maxLevel.

**Comment by mosheduminer** [comment]
It seems to me that `maxLevel=1` returns only the node specified. This means that if I hover the mouse over `node=12` when `maxLevel=1`, then _only node 12_ is returned, and _no subnodes_. I think that we must disable a value of 0 for lazy loading, else it will be impossible to (lazy) load deeper. I also fixed the issue above (regarding expecting an array instead of an object), and saw that it was now impossible to lazy load. I do think that the solution is to not allow a `maxLevel=1`.
